/* eslint-disable no-dupe-keys */
// --------------------- УНИВЕРСАЛЬНЫЙ МАППИНГ ПОЛЕЙ (РАСШИРЕННЫЙ ДЛЯ ПОСТАВЩИКОВ) ---------------------
export const FIELD_MAP = {
  // === Основные поля ===
  "название": "name",
  "наименование": "name",
  "товар": "name",
  "продукт": "name",
  "name": "name",
  "title": "name",
  "наименование товара": "name",
  "имя": "name",

  "цена": "price",
  "стоимость": "price",
  "цена руб": "price",
  "цена, руб": "price",
  "price": "price",
  "цены": "price",
  "oldprice": "oldPrice",
  "old_price": "oldPrice",

  "артикул": "sku",
  "sku": "sku",
  "код": "sku",
  "код товара": "sku",
  "vendorcode": "sku",
  "vendor_code": "sku",
  "vendorcode": "vendorCode",
  "арт": "sku",
  "артикул производителя": "sku",
  "ean": "ean",
  "mpn": "mpn",
  "gtin": "gtin",
  "upc": "upc",
  "barcode": "barcode",

  "количество": "quantity",
  "кол-во": "quantity",
  "остаток": "quantity",
  "в наличии": "quantity",
  "qty": "quantity",
  "stock": "quantity",
  "quantity": "quantity",
  "minimumorderquantity": "minOrderQty",
  "кол-во позиций у поворотного механизма": "rotationPositionsCount",
  "кол-во позиций": "positionsCount",
  "кол-во ключей": "keysCount",
  "количество позиций": "positionsQuantity",
  "количество на паллете": "palletQuantity",
  "количество в коробке": "boxQuantity",
  "количество ручьев": "groovesQuantity",
  "количество секций": "sectionsQuantity",
  "количество присосок": "suctionCupsQuantity",
  "количество штук": "piecesQuantity",
  "количество компонентов": "componentsQuantity",
  "количество ступеней": "stepsQuantity",

  "описание": "description",
  "описание товара": "description",
  "полное описание": "description",
  "description": "description",
  "детали": "description",
  "детальное описание": "detailedDescription",
  "детальное описание текстом": "detailedDescriptionText",

  "бренд": "brand",
  "производитель": "brand",
  "марка": "brand",
  "brand": "brand",
  "vendor": "brand",
  "@vendor": "brand",

  "категория": "category",
  "раздел": "category",
  "группа": "category",
  "category": "category",
  "категории": "category",

  // === Физические характеристики ===
  "вес": "weight",
  "weight": "weight",
  "масса": "weight",
  "weightpacked": "weightPacked",
  "packageweight": "weightPacked",
  "масса нетто": "netWeight",

  "габариты": "dimensions",
  "размеры": "dimensions",
  "длина": "length",
  "ширина": "width",
  "высота": "height",
  "глубина": "depth",
  "dimensions": "dimensions",
  "dimensionspacked": "dimensionsPacked",
  "packagedimensions": "dimensionsPacked",
  "размер, мм": "sizeMm",
  "размер гранул": "granuleSize",
  "размер монтажного клина": "mountingWedgeSize",
  "размер уголка": "cornerSize",
  "размер уплотнителя": "sealantSize",
  "длина петли": "hingeLength",
  "высота петли": "hingeHeight",
  "размер цилиндра": "cylinderSize",
  "длина цилиндра": "cylinderLength",
  "диаметр, мм": "diameterMm",
  "ширина ленты": "tapeWidth",
  "длина ленты": "tapeLength",
  "толщина бутилового слоя": "butylLayerThickness",
  "ширина нащельника": "trimWidth",
  "длина намотки, м": "windingLengthM",
  "длина нащельника": "trimLength",
  "толщина ленты": "tapeThickness",
  "ширина малярной полосы": "maskingStripWidth",
  "высота": "height",
  "ширина": "width",
  "размер метиза": "fastenerSize",
  "размер пластины": "plateSize",
  "размер метизов, мм": "fastenersSizeMm",
  "диаметр ствола": "barrelDiameter",
  "длинна ствола": "barrelLength",
  "длина бура": "drillLength",
  "общая длина": "totalLength",
  "длина полотна": "bladeLength",
  "посадка, мм": "mountingMm",
  "высота алмазного слоя": "diamondLayerHeight",
  "диаметр диска": "diskDiameter",
  "посадочный диаметр": "boreDiameter",
  "ширина лезвия": "bladeWidth",
  "максимальный диаметр": "maxDiameter",
  "рабочая область": "workingArea",
  "размер бруска": "whetstoneSize",
  "вес бойка": "strikerWeight",
  "вес головки": "headWeight",
  "минимальное раскрытие губок": "minJawOpening",
  "диаметр бойка": "strikerDiameter",
  "размеры кейса": "caseDimensions",
  "длина стержня": "rodLength",
  "глубина зажима": "clampDepth",
  "ширина зажима": "clampWidth",
  "максимальное раскрытие губок": "maxJawOpening",
  "ширина губок тисков": "viseJawWidth",
  "диаметр хомута": "clampDiameter",
  "длина ворса": "pileLength",
  "размер комбинезона": "overallsSize",
  "штук в мешке": "piecesInBag",
  "рост": "heightPerson",
  "размер перчаток": "glovesSize",
  "для щелей, мм": "forGapsMm",
  "размер головки": "headSize",
  "межосевое расстояние": "centerDistance",
  "дорнмасс": "dornmass",
  "вес двери": "doorWeight",
  "размер": "size",

  "объем": "volume",
  "volume": "volume",
  "volumePacked": "volumePacked",
  "packagevolume": "volumePacked",
  "объём": "volume",
  "объём картриджа": "cartridgeVolume",
  "объём клея": "glueVolume",

  "страна": "country",
  "страна производства": "countryOfOrigin",
  "country": "country",
  "country_of_origin": "countryOfOrigin",
  "страна бренда": "brandCountry",

  "гарантия": "warranty",
  "warranty": "warranty",
  "warrantyperiod": "warrantyPeriod",
  "warrantyextensions": "warrantyExtensions",

  "картинка": "image",
  "изображение": "image",
  "фото": "image",
  "picture": "image",
  "url картинки": "image",
  "photo": "image",
  "images": "images",
  "@images": "images",
  "изображения": "images",
  "фото товара": "images",
  "детальное фото": "mainImage",
  "дополнительные фото": "additionalImages",

  "валюта": "currency",
  "currency": "currency",
  "валюта цены": "currency",

  // === YML атрибуты ===
  "@id": "id",
  "id": "id",
  "@available": "available",
  "available": "available",
  "@type": "offerType",
  "type": "offerType",
  "@group_id": "groupId",
  "sale": "sale",
  "@sale": "sale",

  // === Ценообразование и акции ===
  "discount": "discount",
  "@discount": "discount",
  "sale": "sale",
  "@sale": "sale",
  "bulkpricing": "bulkPricing",

  // === Логистика ===
  "delivery": "delivery",
  "@delivery": "delivery",
  "pickup": "pickup",
  "@pickup": "pickup",
  "deliverytime": "deliveryTime",
  "leadtime": "leadTime",
  "shippingmethod": "shippingMethod",
  "в упаковке": "inPackage",
  "упаковка ленты": "tapePackaging",
  "упаковка, комплектация": "packagingCompleteness",
  "упаковка большая": "largePackaging",
  "упаковка маленькая": "smallPackaging",
  "минимальная упаковка": "minPackaging",
  "индивидуальная упаковка": "individualPackaging",

  // === Технические характеристики (из optimus.su и типичных YML) ===
  "color": "color",
  "@color": "color",
  "цвет": "color",

  "материал": "material",
  "@material": "material",
  "материал корпуса": "bodyMaterial",
  "материал покрытия": "coatingMaterial",
  "материал рукоятки": "handleMaterial",
  "корпус": "body",
  "материал адаптера": "adapterMaterial",
  "материал регулировочного винта": "adjustmentScrewMaterial",
  "материал сопла": "nozzleMaterial",
  "материал ствола": "barrelMaterial",
  "материал бойка": "strikerMaterial",
  "материал ленты": "tapeMaterial",
  "материал стержня": "rodMaterial",
  "материал основы": "baseMaterial",
  "материал обработки": "processingMaterial",
  "подкладка": "lining",
  "утеплитель": "insulator",
  "наладонник": "palmPad",
  "покрытие перчаток": "glovesCoating",
  "покрытие": "coating",
  "поверхность": "surface",
  "основа": "base",
  "цвет основы": "baseColor",

  "мощность": "power",
  "power": "power",
  "@power": "power",

  "напряжение": "voltage",
  "@voltage": "voltage",

  "частота": "frequency",
  "@frequency": "frequency",

  "давление": "pressure",
  "@pressure": "pressure",
  "максимальное давление": "maxPressure",
  "предел водонепроницаемости (па)": "waterproofLimitPa",
  "сопротивление сжатию при 50% деформации, кпа, не менее": "compressionResistanceKpa",

  "производительность": "productivity",
  "@productivity": "productivity",

  "объем ресивера": "receiverVolume",
  "@receiver_volume": "receiverVolume",

  "количество цилиндров": "cylindersNumber",
  "@cylinders_number": "cylindersNumber",

  "смазка маслом": "oilLubricated",
  "@oil_lubricated": "oilLubricated",

  "безмасляный": "oilFree",
  "@oil_free": "oilFree",

  "тип подключения": "connectionType",
  "@connection_type": "connectionType",
  "тип": "type",
  "тип товара": "productType",
  "тип молекулярного сито": "molecularSieveType",
  "тип окон": "windowType",
  "тип ленты": "tapeType",
  "тип герметизирующего материала": "sealantMaterialType",
  "тип цилиндра": "cylinderType",
  "тип краски": "paintType",
  "верхний душ": "topShower",
  "встраиваемый": "builtIn",
  "тип излива": "spoutType",
  "под фильтр": "underFilter",
  "серия": "series",
  "аэратор": "aerator",
  "подводка": "liner",
  "безободковый": "rimless",
  "быстросъемное сидение": "quickReleaseSeat",
  "фасовка, шт.": "packagingPcs",
  "коробка, пар.": "boxPairs",
  "тип головки": "headType",
  "тип шлица": "slotType",
  "наконечник": "tip",
  "резьба": "thread",
  "корпус пистолета": "pistolBody",
  "назначение пистолета": "pistolPurpose",
  "тип ствола": "barrelType",
  "шарик клапана": "valveBall",
  "тип режущего инструмента": "cuttingToolType",
  "хвостовики": "shanks",
  "тип патрона": "chuckType",
  "типы буров и насадок": "drillsAndAttachmentsTypes",
  "тип диска": "diskType",
  "марка стали": "steelGrade",
  "тип хвостика": "shankType",
  "тип наконечника": "tipType",
  "вид": "view",
  "форма": "shape",
  "типы ножей": "knivesTypes",
  "тип ножниц": "scissorsType",
  "углы установки полотна": "bladeInstallationAngles",
  "тип полотна": "bladeType",
  "tpi": "tpi",
  "абразив": "abrasive",
  "тип кусачек": "nippersType",
  "тип длинногубцев": "longNosePliersType",
  "форма бойка": "strikerShape",
  "тип молотка": "hammerType",
  "состав набора": "setComposition",
  "тип измерительного инструмента": "measuringToolType",
  "вид крепежного инструмента": "fasteningToolType",
  "размер заклепок": "rivetsSize",
  "тип заклепочника\\заклепок": "riveterRivetType",
  "длинна заклепочника": "riveterLength",
  "регулировка силы удара": "impactForceAdjustment",
  "тип скоб": "staplesType",
  "тип степлера": "staplerType",
  "минимальная t° обработки": "minProcessingTemp",
  "жизнеспособность смеси": "mixtureViability",
  "жизнеспособность при температуре 20°с": "viabilityAt20C",
  "№ (номер)": "number",
  "плотность г/м2": "densityGm2",
  "застежка": "fastener",
  "подлежит обязательной сертификации": "mandatoryCertification",
  "ладонная часть": "palmPart",
  "класс вязки": "knittingClass",
  "плотность наладонника": "palmPadDensity",
  "виды уплотнителя": "sealantTypes",
  "внешний вид уплотнителя": "sealantAppearance",
  "тип уплотнителя": "sealantType",
  "водопоглащение": "waterAbsorption",
  "назначение инструмента": "toolPurpose",
  "тип защелки": "latchType",

  "емкость": "capacity",
  "@capacity": "capacity",

  "размер": "size",
  "@size": "size",

  "единица": "unit",
  "@unit": "unit",

  "мера": "measure",
  "@measure": "measure",

  "доставка": "delivery",

  "@delivery": "delivery",

  "самовывоз": "pickup",
  "@pickup": "pickup",

  "таможня": "customs",
  "@customs": "customs",

  "доступность": "availability",
  "@availability": "availability",

  // === Сертификация и экология ===
  "сертификация": "certification",
  "@certification": "certification",
  "стандарты": "standards",
  "@standards": "standards",
  "безопасность": "safety",
  "@safety": "safety",
  "экологичность": "environmental",
  "@environmental": "environmental",
  "утилизация": "disposal",
  "@disposal": "disposal",
  "переработка": "recycling",
  "@recycling": "recycling",
  "энергоэффективность": "energyEfficiency",
  "@energyEfficiency": "energyEfficiency",
  "источник питания": "powerSource",
  "@powerSource": "powerSource",
  "ток": "current",
  "@current": "current",
  "обороты": "rpm",
  "@rpm": "rpm",
  "крутящий момент": "torque",
  "@torque": "torque",
  "скорость": "speed",
  "@speed": "speed",
  "диапазон": "range",
  "@range": "range",
  "разрешение": "resolution",
  "@resolution": "resolution",
  "точность": "accuracy",
  "@accuracy": "accuracy",
  "температура работы": "operatingTemperature",
  "@operatingTemperature": "operatingTemperature",
  "температура хранения": "storageTemperature",
  "@storageTemperature": "storageTemperature",
  "влажность": "humidity",
  "@humidity": "humidity",
  "уровень шума": "noiseLevel",
  "@noiseLevel": "noiseLevel",
  "вибрация": "vibration",
  "@vibration": "vibration",
  "класс защиты": "protectionClass",
  "@protectionClass": "protectionClass",
  "ip рейтинг": "ipRating",
  "@ipRating": "ipRating",
  "ik рейтинг": "ikRating",
  "@ikRating": "ikRating",
  "сертификаты": "certificates",
  "@certificates": "certificates",
  "срок службы": "serviceLife",
  "@serviceLife": "serviceLife",
  "обслуживание": "maintenance",
  "@maintenance": "maintenance",
  "смазка": "lubrication",
  "@lubrication": "lubrication",
  "охлаждение": "cooling",
  "@cooling": "cooling",
  "привод": "driveType",
  "@driveType": "driveType",
  "крепление": "mounting",
  "@mounting": "mounting",
  "подключение": "connection",
  "@connection": "connection",
  "интерфейс": "interface",
  "@interface": "interface",
  "порты": "ports",
  "@ports": "ports",
  "кабели": "cables",
  "@cables": "cables",
  "аксессуары": "accessoriesIncluded",
  "@accessoriesIncluded": "accessoriesIncluded",
  "доп аксессуары": "optionalAccessories",
  "@optionalAccessories": "optionalAccessories",
  "программное обеспечение": "software",
  "@software": "software",
  "прошивка": "firmware",
  "@firmware": "firmware",
  "совместимость": "compatibilityNotes",
  "@compatibilityNotes": "compatibilityNotes",
  "установка": "installation",
  "@installation": "installation",
  "эксплуатация": "operation",
  "@operation": "operation",
  "хранение": "storage",
  "@storage": "storage",
  "транспортировка": "transport",
  "@transport": "transport",
  "инструкции по утилизации": "disposalInstructions",
  "@disposalInstructions": "disposalInstructions",
  "инструкции по переработке": "recyclingInstructions",
  "@recyclingInstructions": "recyclingInstructions",
  "влияние на окружающую среду": "environmentalImpact",
  "@environmentalImpact": "environmentalImpact",
  "потребление энергии": "energyConsumption",
  "@energyConsumption": "energyConsumption",
  "выбросы": "emissions",
  "@emissions": "emissions",
  "выброс шума": "noiseEmission",
  "@noiseEmission": "noiseEmission",
  "эргономика": "ergonomics",
  "@ergonomics": "ergonomics",
  "руководство пользователя": "userManual",
  "@userManual": "userManual",
  "инструкции по сборке": "assemblyInstructions",
  "@assemblyInstructions": "assemblyInstructions",
  "инструкции по безопасности": "safetyInstructions",
  "@safetyInstructions": "safetyInstructions",
  "технические характеристики": "technicalSpecifications",
  "@technicalSpecifications": "technicalSpecifications",

  // === Продажи и поддержка ===
  "возврат": "returnPolicy",
  "@returnPolicy": "returnPolicy",
  "возврат денег": "refundPolicy",
  "@refundPolicy": "refundPolicy",
  "обмен": "exchangePolicy",
  "@exchangePolicy": "exchangePolicy",
  "поддержка клиентов": "customerSupport",
  "@customerSupport": "customerSupport",
  "техническая поддержка": "technicalSupportContact",
  "@technicalSupportContact": "technicalSupportContact",
  "контакт продаж": "salesContact",
  "@salesContact": "salesContact",
  "авторизованные центры": "authorizedServiceCenters",
  "@authorizedServiceCenters": "authorizedServiceCenters",
  "ремонт": "repairServices",
  "@repairServices": "repairServices",
  "обслуживание": "maintenanceServices",
  "@maintenanceServices": "maintenanceServices",
  "обучение": "training",
  "@training": "training",

  // === Экология и compliance (расширенно из optimus.su) ===
  "углеродный след": "carbonFootprint",
  "@carbonFootprint": "carbonFootprint",
  "устойчивость": "sustainability",
  "@sustainability": "sustainability",
  "переработанный контент": "recycledContent",
  "@recycledContent": "recycledContent",
  "перерабатываемость": "recyclability",
  "@recyclability": "recyclability",
  "биоразлагаемость": "biodegradability",
  "@biodegradability": "biodegradability",
  "химический состав": "chemicalComposition",
  "@chemicalComposition": "chemicalComposition",
  "аллергены": "allergens",
  "@allergens": "allergens",
  "ограниченные вещества": "restrictedSubstances",
  "@restrictedSubstances": "restrictedSubstances",
  "конфликтные минералы": "conflictMinerals",
  "@conflictMinerals": "conflictMinerals",
  "rohs": "rohsCompliance",
  "@rohsCompliance": "rohsCompliance",
  "reach": "reachCompliance",
  "@reachCompliance": "reachCompliance",
  "weee": "wEEECompliance",
  "@wEEECompliance": "wEEECompliance",
  "ce": "ceMarking",
  "@ceMarking": "ceMarking",
  "ul": "ulCertification",
  "@ulCertification": "ulCertification",
  "cul": "cULCertification",
  "@cULCertification": "cULCertification",
  "etl": "etlCertification",
  "@etlCertification": "etlCertification",
  "nema": "nemaEnclosureType",
  "@nemaEnclosureType": "nemaEnclosureType",
  "iecex": "iecExCertification",
  "@iecExCertification": "iecExCertification",
  "atex": "atexCertification",
  "@atexCertification": "atexCertification",
  "iec стандарты": "iecStandards",
  "@iecStandards": "iecStandards",
  "iso стандарты": "isoStandards",
  "@isoStandards": "isoStandards",
  "astm стандарты": "astmStandards",
  "@astmStandards": "astmStandards",
  "din стандарты": "dinStandards",
  "@dinStandards": "dinStandards",
  "jis": "jisStandards",
  "@jisStandards": "jisStandards",

  // === Дополнительно (для bundle, modular и т.д.) ===
  "модульный дизайн": "modularDesign",
  "@modularDesign": "modularDesign",
  "расширяемость": "expandability",
  "@expandability": "expandability",
  "интеграция": "integration",
  "@integration": "integration",
  "интероперабельность": "interoperability",
  "@interoperability": "interoperability",
  "соответствие стандартам": "standardsCompliance",
  "@standardsCompliance": "standardsCompliance",
  "регуляторные одобрения": "regulatoryApprovals",
  "@regulatoryApprovals": "regulatoryApprovals",
  "экспорт": "exportCompliance",
  "@exportCompliance": "exportCompliance",
  "импорт": "importRestrictions",
  "@importRestrictions": "importRestrictions",
  "налоги": "taxInformation",
  "@taxInformation": "taxInformation",
  "структура цен": "pricingStructure",
  "@pricingStructure": "pricingStructure",
  "скидки": "discounts",
  "@discounts": "discounts",
  "промо": "promotions",
  "@promotions": "promotions",
  "сезонные предложения": "seasonalOffers",
  "@seasonalOffers": "seasonalOffers",
  "пакетные сделки": "bundleDeals",
  "@bundleDeals": "bundleDeals",
  "подписка": "subscriptionOptions",
  "@subscriptionOptions": "subscriptionOptions",
  "лизинг": "leasingOptions",
  "@leasingOptions": "leasingOptions",
  "финансирование": "financingOptions",
  "@financingOptions": "financingOptions",
  "аренда": "rentalOptions",
  "@rentalOptions": "rentalOptions",
  "демо": "demoUnits",
  "@demoUnits": "demoUnits",
  "пробный период": "trialPeriods",
  "@trialPeriods": "trialPeriods",
  "сервисные контракты": "serviceContracts",
  "@serviceContracts": "serviceContracts",
  "программы обновления": "upgradePrograms",
  "@upgradePrograms": "upgradePrograms",
  "программы лояльности": "loyaltyPrograms",
  "@loyaltyPrograms": "loyaltyPrograms",

  // === Новые поля из Zalivka_stroyst.xlsx и optimus.su ===
  "ссылка": "url",
  "пустое поле 2": "emptyField2",
  "пустое поле 3": "emptyField3",
  "штифт": "pin",
  "крепление": "mounting",
  "назначение уплотнителя": "sealantPurpose",
  "фурнитурный паз": "fittingGroove",
  "t° применения": "applicationTemp",
  "наши предложения": "ourOffers",
  "сезонность пены": "foamSeasonality",
  "время образования пленки": "filmFormationTime",
  "время предварительной обработки": "preProcessingTime",
  "вторичное расширение": "secondaryExpansion",
  "выход": "output",
  "температура баллона": "cylinderTemp",
  "срок хранения": "shelfLife",
  "время полной полимеризации": "fullPolymerizationTime",
  "время высыхания поверхности": "surfaceDryingTime",
  "t° хранения": "storageTemp",
  "время затвердевания": "hardeningTime",
  "температура монтажа (применения)": "mountingTemp",
  "t° использования": "usageTemp",
  "линейка": "line",
  "твердость (по шору а)": "shoreAHardness",
  "максимальное растяжение": "maxElongation",
  "вид герметика": "sealantType",
  "тип шва": "jointType",
  "относительное удлинение при разрыве,%": "elongationAtBreakPercent",
  "область применения": "applicationArea",
  "сухой остаток": "dryResidue",
  "плотность": "density",
  "назначение": "purpose",
  "подвижность шва": "jointMobility",
  "устойчивость к температуре (°c)": "tempResistanceC",
  "t° эксплуатации": "operatingTemp",
  "видео (код из youtube)": "youtubeVideoCode",
  "предел прочности": "strengthLimit",
  "180° прочность на отслаивание": "peelStrength180",
  "скорость отверждения": "curingSpeed",
  "удельный вес, гр/см3": "specificGravityGcm3",
  "максимальное расширение ленты": "maxTapeExpansion",
  "воздухопроницаемость": "airPermeability",
  "долговечность": "durability",
  "коэффициент паропроницаемости материала": "vaporPermeabilityCoeff",
  "прочность сцепления (адгезия) с поверхностями проёмов и коробок, не менее (мпа)": "adhesionStrengthMpa",
  "сопротивление паропроницанию": "vaporResistance",
  "устойчивость к впитыванию воды (па)": "waterAbsorptionResistancePa",
  "время высыхания": "dryingTime",
  "срок службы": "serviceLife",
  "адгезионная прочност": "adhesiveStrength",
  "водопоглощение при частичном погружении на 24 ч, % по объему, не более": "waterAbsorption24hPercent",
  "теплостойкость, с, не ниже": "heatResistanceC",
  "стойкость к воздействию ультрафиолетовых лучшей (гдж/м2)": "uvResistanceGJm2",
  "разрывная сила, h": "breakingForceH",
  "время коррекции": "correctionTime",
  "время отверждения": "curingTime",
  "время схватывания": "settingTime",
  "время полного высыхания": "fullDryingTime",
  "выход при склеивании планок": "outputForGluingStrips",
  "время действия вещества": "substanceActionTime",
  "расход": "consumption",
  "коллекция": "collection",
  "защитные свойства": "protectiveProperties",
  "использование": "usage",
  "назначение диска": "diskPurpose",
  "зернистость": "grit",
  "грузоподъемность": "loadCapacity",
  "номер ключа": "keyNumber",
  "передаточное отношение": "gearRatio",
  "усилие подачи": "feedForce",
  "диаметр прута (мягкая сталь)": "rodDiameterSoftSteel",
  "диаметр прута (твердая сталь)": "rodDiameterHardSteel",
  "количество зубьев": "teethCount",
};